/**
 * Built-in curriculum framework definitions.
 * These can be seeded into the database on first setup.
 */

export const BUILT_IN_FRAMEWORKS = [
  {
    code: "GHANA_WAEC",
    name: "Ghana WAEC/WASSCE",
    description: "West African Examinations Council curriculum for Ghana Senior High Schools. 3-year programme with WASSCE final examinations.",
    country: "Ghana",
    organization: "WAEC (West African Examinations Council)",
    gradeLevels: ["SHS 1", "SHS 2", "SHS 3"],
    defaultGradingTemplate: {
      name: "WAEC Standard",
      assessmentWeights: { classwork: 10, homework: 10, project: 10, midterm: 20, exam: 50 },
      gradeScale: [
        { grade: "A1", min: 80, max: 100, gpa: 1.0 },
        { grade: "B2", min: 70, max: 79, gpa: 2.0 },
        { grade: "B3", min: 65, max: 69, gpa: 3.0 },
        { grade: "C4", min: 60, max: 64, gpa: 4.0 },
        { grade: "C5", min: 55, max: 59, gpa: 5.0 },
        { grade: "C6", min: 50, max: 54, gpa: 6.0 },
        { grade: "D7", min: 45, max: 49, gpa: 7.0 },
        { grade: "E8", min: 40, max: 44, gpa: 8.0 },
        { grade: "F9", min: 0, max: 39, gpa: 9.0 },
      ],
      passThreshold: 50,
    },
  },
  {
    code: "CAMBRIDGE_IGCSE",
    name: "Cambridge IGCSE",
    description: "Cambridge International General Certificate of Secondary Education. International qualification for 14-16 year olds.",
    country: "International",
    organization: "Cambridge Assessment International Education",
    gradeLevels: ["Year 10", "Year 11"],
    defaultGradingTemplate: {
      name: "Cambridge IGCSE Standard",
      assessmentWeights: { coursework: 30, exam: 70 },
      gradeScale: [
        { grade: "A*", min: 90, max: 100, gpa: 4.0 },
        { grade: "A", min: 80, max: 89, gpa: 4.0 },
        { grade: "B", min: 70, max: 79, gpa: 3.0 },
        { grade: "C", min: 60, max: 69, gpa: 2.0 },
        { grade: "D", min: 50, max: 59, gpa: 1.0 },
        { grade: "E", min: 40, max: 49, gpa: 1.0 },
        { grade: "F", min: 30, max: 39, gpa: 0.0 },
        { grade: "G", min: 20, max: 29, gpa: 0.0 },
        { grade: "U", min: 0, max: 19, gpa: 0.0 },
      ],
      passThreshold: 40,
    },
  },
  {
    code: "CAMBRIDGE_ALEVEL",
    name: "Cambridge A-Level",
    description: "Cambridge International Advanced Level. Pre-university qualification recognized worldwide.",
    country: "International",
    organization: "Cambridge Assessment International Education",
    gradeLevels: ["AS Level", "A2 Level"],
    defaultGradingTemplate: {
      name: "Cambridge A-Level Standard",
      assessmentWeights: { coursework: 20, exam: 80 },
      gradeScale: [
        { grade: "A*", min: 90, max: 100, gpa: 4.0 },
        { grade: "A", min: 80, max: 89, gpa: 4.0 },
        { grade: "B", min: 70, max: 79, gpa: 3.0 },
        { grade: "C", min: 60, max: 69, gpa: 2.0 },
        { grade: "D", min: 50, max: 59, gpa: 1.0 },
        { grade: "E", min: 40, max: 49, gpa: 1.0 },
        { grade: "U", min: 0, max: 39, gpa: 0.0 },
      ],
      passThreshold: 40,
    },
  },
  {
    code: "IB_DP",
    name: "International Baccalaureate Diploma Programme",
    description: "Two-year educational programme for students aged 16-19. Recognized globally for university admission.",
    country: "International",
    organization: "International Baccalaureate Organization (IBO)",
    gradeLevels: ["IB Year 1", "IB Year 2"],
    defaultGradingTemplate: {
      name: "IB DP Standard",
      assessmentWeights: { internal_assessment: 25, exam: 75 },
      gradeScale: [
        { grade: "7", min: 86, max: 100, gpa: 4.0 },
        { grade: "6", min: 72, max: 85, gpa: 3.7 },
        { grade: "5", min: 58, max: 71, gpa: 3.3 },
        { grade: "4", min: 44, max: 57, gpa: 3.0 },
        { grade: "3", min: 30, max: 43, gpa: 2.0 },
        { grade: "2", min: 16, max: 29, gpa: 1.0 },
        { grade: "1", min: 0, max: 15, gpa: 0.0 },
      ],
      passThreshold: 44,
    },
  },
  {
    code: "US_COMMON_CORE",
    name: "American Common Core",
    description: "US Common Core State Standards with GPA-based grading. Widely used in American-style international schools.",
    country: "United States",
    organization: "Common Core State Standards Initiative",
    gradeLevels: ["Grade 9", "Grade 10", "Grade 11", "Grade 12"],
    defaultGradingTemplate: {
      name: "US GPA Standard",
      assessmentWeights: { classwork: 20, homework: 10, quizzes: 20, midterm: 20, final: 30 },
      gradeScale: [
        { grade: "A+", min: 97, max: 100, gpa: 4.0 },
        { grade: "A", min: 93, max: 96, gpa: 4.0 },
        { grade: "A-", min: 90, max: 92, gpa: 3.7 },
        { grade: "B+", min: 87, max: 89, gpa: 3.3 },
        { grade: "B", min: 83, max: 86, gpa: 3.0 },
        { grade: "B-", min: 80, max: 82, gpa: 2.7 },
        { grade: "C+", min: 77, max: 79, gpa: 2.3 },
        { grade: "C", min: 73, max: 76, gpa: 2.0 },
        { grade: "C-", min: 70, max: 72, gpa: 1.7 },
        { grade: "D", min: 60, max: 69, gpa: 1.0 },
        { grade: "F", min: 0, max: 59, gpa: 0.0 },
      ],
      passThreshold: 60,
    },
  },
] as const;
