import type { Prisma, BalanceSide, JournalStatus } from "@prisma/client";
import { toNum } from "@/lib/decimal";

export type LedgerLineInput = {
  accountId: string;
  side: BalanceSide;
  amount: number;
  narration?: string;
  fundId?: string | null;
};

export type PostJournalInput = {
  schoolId: string;
  date: Date;
  description: string;
  referenceType?: string | null;
  referenceId?: string | null;
  createdBy: string;
  postedBy?: string | null;
  isAutoGenerated?: boolean;
  isAdjusting?: boolean;
  isClosing?: boolean;
  reversalOfId?: string | null;
  /** Every call must pass balanced DEBIT and CREDIT lines. Σdebits must equal Σcredits. */
  lines: LedgerLineInput[];
};

export type LedgerPostingError =
  | { code: "NO_LINES"; message: string }
  | { code: "UNBALANCED"; message: string; totalDebits: number; totalCredits: number }
  | { code: "NEGATIVE_AMOUNT"; message: string }
  | { code: "PERIOD_CLOSED"; message: string; fiscalPeriodId?: string }
  | { code: "ACCOUNT_NOT_FOUND"; message: string; accountId: string }
  | { code: "CROSS_SCHOOL"; message: string; accountId: string };

export class LedgerError extends Error {
  readonly info: LedgerPostingError;
  constructor(info: LedgerPostingError) {
    super(info.message);
    this.name = "LedgerError";
    this.info = info;
  }
}

const EPSILON = 0.005; // half a pesewa tolerance for float rounding

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

/**
 * Central authoritative posting function.
 *
 * Responsibilities:
 *   - Validate that amounts are positive and that Σdebits === Σcredits.
 *   - Resolve the fiscal period covering the transaction date and enforce its status.
 *   - Resolve the default Fund for any line missing `fundId` (school's General Fund).
 *   - Create the JournalTransaction (status=POSTED) and all JournalEntry rows.
 *   - Update Account.currentBalance respecting normalBalance:
 *       if line.side === account.normalBalance → increment by amount
 *       otherwise → decrement by amount.
 *
 * Callers must pass a Prisma transaction client (`tx`) so the ledger write is atomic
 * with the surrounding operational mutation (e.g., marking a waiver APPROVED).
 */
export async function postJournalTransaction(
  tx: Prisma.TransactionClient,
  input: PostJournalInput,
): Promise<{ journalTransactionId: string; transactionNumber: string }> {
  if (input.lines.length === 0) {
    throw new LedgerError({ code: "NO_LINES", message: "A journal transaction must have at least one line." });
  }

  let totalDebits = 0;
  let totalCredits = 0;
  for (const line of input.lines) {
    if (!(line.amount > 0)) {
      throw new LedgerError({ code: "NEGATIVE_AMOUNT", message: `Line amount must be > 0 (got ${line.amount}).` });
    }
    if (line.side === "DEBIT") totalDebits += line.amount;
    else totalCredits += line.amount;
  }

  if (Math.abs(totalDebits - totalCredits) > EPSILON) {
    throw new LedgerError({
      code: "UNBALANCED",
      message: `Journal is not balanced: debits=${round2(totalDebits)}, credits=${round2(totalCredits)}.`,
      totalDebits: round2(totalDebits),
      totalCredits: round2(totalCredits),
    });
  }

  // Resolve accounts and validate tenant isolation
  const accountIds = [...new Set(input.lines.map((l) => l.accountId))];
  const accounts = await tx.account.findMany({
    where: { id: { in: accountIds } },
    select: { id: true, schoolId: true, normalBalance: true, code: true },
  });
  const accountMap = new Map(accounts.map((a) => [a.id, a]));
  for (const line of input.lines) {
    const acc = accountMap.get(line.accountId);
    if (!acc) {
      throw new LedgerError({ code: "ACCOUNT_NOT_FOUND", message: `Account ${line.accountId} not found.`, accountId: line.accountId });
    }
    if (acc.schoolId !== input.schoolId) {
      throw new LedgerError({ code: "CROSS_SCHOOL", message: `Account ${acc.code} belongs to another school.`, accountId: line.accountId });
    }
  }

  // Resolve fiscal period (optional — if none configured for the school, we skip enforcement)
  const fiscalPeriod = await tx.fiscalPeriod.findFirst({
    where: {
      schoolId: input.schoolId,
      startDate: { lte: input.date },
      endDate: { gte: input.date },
      isFiscalYear: false, // prefer the narrowest sub-period
    },
    orderBy: { startDate: "desc" },
  }) ?? await tx.fiscalPeriod.findFirst({
    where: {
      schoolId: input.schoolId,
      startDate: { lte: input.date },
      endDate: { gte: input.date },
    },
    orderBy: { startDate: "desc" },
  });

  if (fiscalPeriod) {
    if (fiscalPeriod.status === "CLOSED") {
      throw new LedgerError({
        code: "PERIOD_CLOSED",
        message: `Fiscal period "${fiscalPeriod.name}" is closed — cannot post on ${input.date.toISOString().slice(0, 10)}.`,
        fiscalPeriodId: fiscalPeriod.id,
      });
    }
    if (fiscalPeriod.status === "SOFT_CLOSED" && !input.isAdjusting && !input.isClosing) {
      throw new LedgerError({
        code: "PERIOD_CLOSED",
        message: `Fiscal period "${fiscalPeriod.name}" is soft-closed — only adjusting/closing entries allowed.`,
        fiscalPeriodId: fiscalPeriod.id,
      });
    }
  }

  // Resolve default fund (school's General Fund) for lines missing fundId
  const defaultFund = await tx.fund.findFirst({
    where: { schoolId: input.schoolId, isDefault: true, isActive: true },
    select: { id: true },
  });

  const transactionNumber = await nextTransactionNumber(tx, input.schoolId, input.date);

  const txn = await tx.journalTransaction.create({
    data: {
      schoolId: input.schoolId,
      transactionNumber,
      date: input.date,
      description: input.description,
      referenceType: input.referenceType ?? null,
      referenceId: input.referenceId ?? null,
      fiscalPeriodId: fiscalPeriod?.id ?? null,
      isAutoGenerated: input.isAutoGenerated ?? false,
      isAdjusting: input.isAdjusting ?? false,
      isClosing: input.isClosing ?? false,
      reversalOfId: input.reversalOfId ?? null,
      createdBy: input.createdBy,
      postedBy: input.postedBy ?? input.createdBy,
      postedAt: new Date(),
      status: "POSTED" as JournalStatus,
    },
  });

  await tx.journalEntry.createMany({
    data: input.lines.map((line, index) => ({
      schoolId: input.schoolId,
      journalTransactionId: txn.id,
      accountId: line.accountId,
      fundId: line.fundId ?? defaultFund?.id ?? null,
      side: line.side,
      amount: round2(line.amount),
      narration: line.narration ?? null,
      lineOrder: index,
    })),
  });

  // Update account balances respecting normalBalance direction
  for (const line of input.lines) {
    const acc = accountMap.get(line.accountId)!;
    const delta = line.side === acc.normalBalance ? line.amount : -line.amount;
    await tx.account.update({
      where: { id: line.accountId },
      data: { currentBalance: { increment: round2(delta) } },
    });
  }

  return { journalTransactionId: txn.id, transactionNumber };
}

/**
 * Create a balanced counter-entry that reverses a POSTED transaction and marks
 * the original REVERSED. Returns the id of the new reversing transaction.
 */
export async function reverseJournalTransaction(
  tx: Prisma.TransactionClient,
  originalId: string,
  opts: { schoolId: string; reversedBy: string; description?: string; date?: Date },
): Promise<{ journalTransactionId: string; transactionNumber: string }> {
  const original = await tx.journalTransaction.findUnique({
    where: { id: originalId },
    include: { entries: true },
  });
  if (!original) throw new LedgerError({ code: "ACCOUNT_NOT_FOUND", message: `Journal ${originalId} not found.`, accountId: originalId });
  if (original.schoolId !== opts.schoolId) {
    throw new LedgerError({ code: "CROSS_SCHOOL", message: "Cross-school reversal forbidden.", accountId: originalId });
  }
  if (original.status === "REVERSED") {
    throw new LedgerError({ code: "UNBALANCED", message: `Journal ${original.transactionNumber} already reversed.`, totalDebits: 0, totalCredits: 0 });
  }
  if (original.status !== "POSTED") {
    throw new LedgerError({ code: "UNBALANCED", message: `Only POSTED journals can be reversed.`, totalDebits: 0, totalCredits: 0 });
  }

  const reverseLines: LedgerLineInput[] = original.entries.map((e) => ({
    accountId: e.accountId,
    side: e.side === "DEBIT" ? "CREDIT" : ("DEBIT" as BalanceSide),
    amount: toNum(e.amount),
    narration: `Reversal: ${e.narration ?? ""}`.trim(),
    fundId: e.fundId,
  }));

  const result = await postJournalTransaction(tx, {
    schoolId: opts.schoolId,
    date: opts.date ?? new Date(),
    description: opts.description ?? `Reversal of ${original.transactionNumber}: ${original.description}`,
    referenceType: "Reversal",
    referenceId: originalId,
    createdBy: opts.reversedBy,
    isAutoGenerated: true,
    reversalOfId: originalId,
    lines: reverseLines,
  });

  await tx.journalTransaction.update({
    where: { id: originalId },
    data: { status: "REVERSED", reversedBy: opts.reversedBy, reversedAt: new Date() },
  });

  return result;
}

/**
 * Generate the next JRN/YYYY/NNNN transaction number for a school.
 * Uses the transaction's year (not today's year) to ensure back-dated entries
 * stay numerically grouped with their peers.
 */
export async function nextTransactionNumber(
  tx: Prisma.TransactionClient,
  schoolId: string,
  forDate: Date,
): Promise<string> {
  const year = forDate.getFullYear();
  const prefix = `JRN/${year}/`;
  const last = await tx.journalTransaction.findFirst({
    where: { schoolId, transactionNumber: { startsWith: prefix } },
    orderBy: { transactionNumber: "desc" },
    select: { transactionNumber: true },
  });
  const nextNum = last ? parseInt(last.transactionNumber.split("/").pop()!, 10) + 1 : 1;
  return `${prefix}${String(nextNum).padStart(4, "0")}`;
}

/**
 * Resolve an Account by code for the given school. Returns null if the COA hasn't
 * been seeded yet (callers can skip journal posting gracefully in that case).
 */
export async function findAccountByCode(
  tx: Prisma.TransactionClient,
  schoolId: string,
  code: string,
): Promise<{ id: string; code: string; normalBalance: BalanceSide } | null> {
  return tx.account.findFirst({
    where: { schoolId, code },
    select: { id: true, code: true, normalBalance: true },
  });
}

/**
 * Recompute Account.currentBalance for every account in the school from its
 * POSTED journal lines. Call after fixing ledger bugs or after data imports to
 * repair drift. Returns a diff report so ops can see what changed.
 */
export async function recomputeAccountBalances(
  tx: Prisma.TransactionClient,
  schoolId: string,
): Promise<Array<{ accountId: string; code: string; previous: number; recomputed: number; delta: number }>> {
  const accounts = await tx.account.findMany({
    where: { schoolId },
    select: { id: true, code: true, normalBalance: true, currentBalance: true },
  });
  // Include POSTED + REVERSED journals. A reversal is a *new* journal with its
  // own POSTED entries that counter the original; the original is flagged
  // REVERSED but its entries stay in the database as an audit trail. The live
  // `currentBalance` was updated in real time for both the original and the
  // counter-entry, so replaying them both here reproduces the same total.
  const entries = await tx.journalEntry.findMany({
    where: { schoolId, journalTransaction: { status: { in: ["POSTED", "REVERSED"] } } },
    select: { accountId: true, side: true, amount: true },
  });

  const totals = new Map<string, number>();
  for (const acc of accounts) totals.set(acc.id, 0);
  for (const e of entries) {
    const acc = accounts.find((a) => a.id === e.accountId);
    if (!acc) continue;
    const delta = e.side === acc.normalBalance ? toNum(e.amount) : -toNum(e.amount);
    totals.set(acc.id, (totals.get(acc.id) ?? 0) + delta);
  }

  const diffs: Array<{ accountId: string; code: string; previous: number; recomputed: number; delta: number }> = [];
  for (const acc of accounts) {
    const recomputed = round2(totals.get(acc.id) ?? 0);
    const previous = round2(toNum(acc.currentBalance));
    if (Math.abs(recomputed - previous) > EPSILON) {
      await tx.account.update({ where: { id: acc.id }, data: { currentBalance: recomputed } });
      diffs.push({ accountId: acc.id, code: acc.code, previous, recomputed, delta: round2(recomputed - previous) });
    }
  }
  return diffs;
}
