"use server";

import { db } from "@/lib/db";
import { requireSchoolContext } from "@/lib/auth-context";
import { PERMISSIONS, assertPermission } from "@/lib/permissions";
import { audit } from "@/lib/audit";
import { toNum } from "@/lib/decimal";
import { postJournalTransaction, findAccountByCode, LedgerError } from "@/modules/accounting/lib/ledger";
import { ACCOUNTS } from "@/modules/accounting/lib/account-codes";
import { generateReceivablesAgingAction } from "./financial-reports.action";

/**
 * Apply IPSAS 29/41 expected credit loss (ECL) as an adjusting journal:
 *   Dr Bad Debt Expense (5910) / Cr Allowance for Doubtful Receivables (1402, contra-asset)
 *
 * The delta (new required allowance − existing allowance balance) is what's posted.
 * Running this repeatedly at period-ends will correctly adjust the allowance up or down.
 */
export async function applyImpairmentAction(asOfDate: Date = new Date()) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.JOURNAL_POST);
  if (denied) return denied;

  const agingResult = await generateReceivablesAgingAction(asOfDate);
  if ("error" in agingResult) return agingResult;
  const aging = agingResult.data;

  try {
    const result = await db.$transaction(async (tx) => {
      const allowance = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.ALLOWANCE_DOUBTFUL_RECEIVABLES);
      const badDebt = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.EXPENSE_BAD_DEBT);
      if (!allowance || !badDebt) {
        throw new LedgerError({ code: "ACCOUNT_NOT_FOUND", message: "Allowance for Doubtful Receivables (1402) or Bad Debt Expense (5910) missing.", accountId: "" });
      }

      const currentAllowance = await tx.account.findUnique({ where: { id: allowance.id }, select: { currentBalance: true } });
      const existing = toNum(currentAllowance?.currentBalance);
      const required = aging.totalAllowance;
      const delta = Math.round((required - existing) * 100) / 100;

      let journalId: string | null = null;
      if (Math.abs(delta) >= 0.01) {
        const posted = await postJournalTransaction(tx, {
          schoolId: ctx.schoolId,
          date: asOfDate,
          description: `Receivables impairment — ECL adjusted to GHS ${required.toFixed(2)} (delta ${delta.toFixed(2)})`,
          referenceType: "Impairment",
          createdBy: ctx.session.user.id,
          isAutoGenerated: true,
          isAdjusting: true,
          lines: delta >= 0
            ? [
                { accountId: badDebt.id, side: "DEBIT", amount: delta, narration: "ECL increase" },
                { accountId: allowance.id, side: "CREDIT", amount: delta, narration: "Allowance increase" },
              ]
            : [
                { accountId: allowance.id, side: "DEBIT", amount: -delta, narration: "Allowance release" },
                { accountId: badDebt.id, side: "CREDIT", amount: -delta, narration: "ECL reversal" },
              ],
        });
        journalId = posted.journalTransactionId;
      }

      await tx.impairmentRun.create({
        data: {
          schoolId: ctx.schoolId,
          asOfDate,
          totalReceivables: aging.totalReceivables,
          totalAllowance: required,
          journalTransactionId: journalId,
          generatedBy: ctx.session.user.id,
          buckets: {
            buckets: aging.buckets,
            eclRates: aging.eclRates,
            allowancePerBucket: aging.allowancePerBucket,
          },
        },
      });

      return { previousAllowance: existing, newAllowance: required, delta, journalId };
    });

    await audit({
      userId: ctx.session.user.id,
      action: "CREATE",
      entity: "ImpairmentRun",
      entityId: ctx.schoolId,
      module: "accounting",
      description: `Receivables impairment applied: allowance ${result.previousAllowance.toFixed(2)} → ${result.newAllowance.toFixed(2)}`,
      newData: result,
    });

    return { data: result };
  } catch (err) {
    if (err instanceof LedgerError) return { error: err.message };
    throw err;
  }
}

/**
 * Write off a specific bill as uncollectible. Posts: Dr Allowance / Cr Accounts Receivable
 * (assuming ECL was previously accrued). If no allowance covers it, the balance falls
 * through to Bad Debt Expense instead.
 */
export async function writeOffBillAction(billId: string, reason: string) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.JOURNAL_POST);
  if (denied) return denied;

  const bill = await db.studentBill.findUnique({ where: { id: billId } });
  if (!bill) return { error: "Bill not found" };
  if (bill.schoolId !== ctx.schoolId) return { error: "Access denied" };
  const outstanding = toNum(bill.balanceAmount);
  if (outstanding <= 0) return { error: "Bill has no outstanding balance" };

  try {
    await db.$transaction(async (tx) => {
      const allowance = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.ALLOWANCE_DOUBTFUL_RECEIVABLES);
      const badDebt = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.EXPENSE_BAD_DEBT);
      const ar = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.FEES_RECEIVABLE);
      if (!ar) throw new LedgerError({ code: "ACCOUNT_NOT_FOUND", message: "Accounts Receivable missing.", accountId: "" });

      const allowanceBal = allowance
        ? toNum((await tx.account.findUnique({ where: { id: allowance.id }, select: { currentBalance: true } }))?.currentBalance)
        : 0;
      const useAllowance = Math.min(outstanding, allowanceBal);
      const directBadDebt = outstanding - useAllowance;

      const lines: Array<{ accountId: string; side: "DEBIT" | "CREDIT"; amount: number; narration: string }> = [];
      if (useAllowance > 0 && allowance) {
        lines.push({ accountId: allowance.id, side: "DEBIT", amount: useAllowance, narration: `Write-off bill ${billId.slice(-8)}` });
      }
      if (directBadDebt > 0 && badDebt) {
        lines.push({ accountId: badDebt.id, side: "DEBIT", amount: directBadDebt, narration: `Write-off bill ${billId.slice(-8)}` });
      }
      lines.push({ accountId: ar.id, side: "CREDIT", amount: outstanding, narration: `Write-off bill ${billId.slice(-8)} — ${reason}` });

      const posted = await postJournalTransaction(tx, {
        schoolId: ctx.schoolId,
        date: new Date(),
        description: `Bill write-off — ${reason}`,
        referenceType: "Writeoff",
        referenceId: billId,
        createdBy: ctx.session.user.id,
        isAutoGenerated: true,
        isAdjusting: true,
        lines,
      });

      await tx.studentBill.update({
        where: { id: billId },
        data: {
          writtenOffAmount: { increment: outstanding },
          balanceAmount: 0,
          status: "WAIVED",
          writeOffJournalId: posted.journalTransactionId,
        },
      });
    });

    await audit({
      userId: ctx.session.user.id,
      action: "UPDATE",
      entity: "StudentBill",
      entityId: billId,
      module: "finance",
      description: `Wrote off bill (outstanding GHS ${outstanding.toFixed(2)}): ${reason}`,
    });

    return { data: { success: true } };
  } catch (err) {
    if (err instanceof LedgerError) return { error: err.message };
    throw err;
  }
}
