"use server";

import { db } from "@/lib/db";
import { requireSchoolContext } from "@/lib/auth-context";
import { audit } from "@/lib/audit";
import { PERMISSIONS, assertPermission } from "@/lib/permissions";
import { toNum } from "@/lib/decimal";
import {
  recordPaymentSchema,
  initiateReversalSchema,
  type RecordPaymentInput,
  type InitiateReversalInput,
} from "@/modules/finance/schemas/payment.schema";
import {
  postJournalTransaction,
  reverseJournalTransaction,
  findAccountByCode,
  LedgerError,
} from "@/modules/accounting/lib/ledger";
import { ACCOUNTS, accountCodeForPaymentMethod } from "@/modules/accounting/lib/account-codes";

async function generateReceiptNumber(termId: string): Promise<string> {
  const term = await db.term.findUnique({
    where: { id: termId },
    include: { academicYear: true },
  });

  const year = term ? new Date(term.academicYear.startDate).getFullYear() : new Date().getFullYear();
  const termNumber = term?.termNumber ?? 1;

  const prefix = `RCP/${year}/T${termNumber}/`;
  const lastReceipt = await db.receipt.findFirst({
    where: { receiptNumber: { startsWith: prefix } },
    orderBy: { receiptNumber: "desc" },
  });

  let nextNumber = 1;
  if (lastReceipt) {
    const parts = lastReceipt.receiptNumber.split("/");
    const lastNum = parseInt(parts[parts.length - 1], 10);
    if (!isNaN(lastNum)) nextNumber = lastNum + 1;
  }

  return `${prefix}${String(nextNumber).padStart(4, "0")}`;
}

export async function recordPaymentAction(data: RecordPaymentInput) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_CREATE);
  if (denied) return denied;

  const parsed = recordPaymentSchema.safeParse(data);
  if (!parsed.success) return { error: "Invalid input", details: parsed.error.flatten().fieldErrors };

  const bill = await db.studentBill.findUnique({ where: { id: parsed.data.studentBillId } });
  if (!bill) return { error: "Student bill not found" };
  if (parsed.data.amount <= 0) return { error: "Payment amount must be greater than zero" };
  if (parsed.data.paymentMethod !== "CASH" && !parsed.data.referenceNumber?.trim()) {
    return { error: "Reference number is required for non-cash payments" };
  }

  try {
    const result = await db.$transaction(async (tx) => {
      const payment = await tx.payment.create({
        data: {
          schoolId: ctx.schoolId,
          studentBillId: bill.id,
          studentId: bill.studentId,
          amount: parsed.data.amount,
          paymentMethod: parsed.data.paymentMethod,
          referenceNumber: parsed.data.referenceNumber || null,
          receivedBy: ctx.session.user.id!,
          status: "CONFIRMED",
          notes: parsed.data.notes || null,
        },
      });

      const newPaidAmount = toNum(bill.paidAmount) + parsed.data.amount;
      const newBalanceAmount = toNum(bill.totalAmount) - newPaidAmount;

      let newStatus: "UNPAID" | "PARTIAL" | "PAID" | "OVERPAID";
      if (newBalanceAmount <= 0 && newPaidAmount > toNum(bill.totalAmount)) newStatus = "OVERPAID";
      else if (newBalanceAmount <= 0) newStatus = "PAID";
      else if (newPaidAmount > 0) newStatus = "PARTIAL";
      else newStatus = "UNPAID";

      await tx.studentBill.update({
        where: { id: bill.id },
        data: {
          paidAmount: newPaidAmount,
          balanceAmount: Math.max(0, newBalanceAmount),
          status: newStatus,
        },
      });

      const receiptNumber = await generateReceiptNumber(bill.termId);
      const receipt = await tx.receipt.create({
        data: {
          schoolId: ctx.schoolId,
          paymentId: payment.id,
          receiptNumber,
        },
      });

      // Double-entry posting: Dr Cash/Bank/MoMo (by payment method) / Cr Accounts Receivable.
      // This is the correct accrual-basis entry when the bill already posted Dr AR / Cr Revenue at generation.
      // If the bill has no accrual journal (legacy data), we fall back to Cr Fee Revenue so totals aren't lost.
      const cashCode = accountCodeForPaymentMethod(parsed.data.paymentMethod);
      const cashAccount = await findAccountByCode(tx, ctx.schoolId, cashCode);
      const arAccount = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.FEES_RECEIVABLE);
      const revenueFallback = await findAccountByCode(tx, ctx.schoolId, ACCOUNTS.FEE_REVENUE_TUITION);

      if (cashAccount && (arAccount || revenueFallback)) {
        const creditAccount = bill.accrualJournalId && arAccount ? arAccount : (arAccount ?? revenueFallback)!;
        const posted = await postJournalTransaction(tx, {
          schoolId: ctx.schoolId,
          date: new Date(),
          description: `Fee payment received via ${parsed.data.paymentMethod.replace("_", " ")} — receipt ${receiptNumber}`,
          referenceType: "Payment",
          referenceId: payment.id,
          createdBy: ctx.session.user.id!,
          isAutoGenerated: true,
          lines: [
            { accountId: cashAccount.id, side: "DEBIT", amount: parsed.data.amount, narration: `Receipt ${receiptNumber}` },
            { accountId: creditAccount.id, side: "CREDIT", amount: parsed.data.amount, narration: `Receipt ${receiptNumber}` },
          ],
        });
        await tx.payment.update({
          where: { id: payment.id },
          data: { journalTransactionId: posted.journalTransactionId },
        });
      }

      return { payment, receipt };
    });

    await audit({
      userId: ctx.session.user.id,
      action: "CREATE",
      entity: "Payment",
      entityId: result.payment.id,
      module: "finance",
      description: `Recorded payment of GHS ${parsed.data.amount.toFixed(2)} via ${parsed.data.paymentMethod}. Receipt: ${result.receipt.receiptNumber}`,
      newData: result,
    });

    return { data: result };
  } catch (err) {
    if (err instanceof LedgerError) return { error: `Ledger posting failed: ${err.message}` };
    throw err;
  }
}

export async function getPaymentsAction(filters?: {
  studentId?: string;
  termId?: string;
  date?: string;
  paymentMethod?: string;
  page?: number;
  pageSize?: number;
}) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_READ);
  if (denied) return denied;

  const page = filters?.page ?? 1;
  const pageSize = filters?.pageSize ?? 25;
  const skip = (page - 1) * pageSize;

  const where: Record<string, unknown> = {};
  if (filters?.studentId) where.studentId = filters.studentId;
  if (filters?.paymentMethod) where.paymentMethod = filters.paymentMethod;

  if (filters?.termId) {
    const bills = await db.studentBill.findMany({
      where: { termId: filters.termId },
      select: { id: true },
    });
    where.studentBillId = { in: bills.map((b) => b.id) };
  }

  if (filters?.date) {
    const dateStart = new Date(filters.date);
    dateStart.setHours(0, 0, 0, 0);
    const dateEnd = new Date(filters.date);
    dateEnd.setHours(23, 59, 59, 999);
    where.receivedAt = { gte: dateStart, lte: dateEnd };
  }

  const [payments, total] = await Promise.all([
    db.payment.findMany({
      where,
      skip,
      take: pageSize,
      include: {
        receipt: true,
        studentBill: {
          select: { id: true, termId: true, totalAmount: true, balanceAmount: true },
        },
      },
      orderBy: { receivedAt: "desc" },
    }),
    db.payment.count({ where }),
  ]);

  const studentIds = [...new Set(payments.map((p) => p.studentId))];
  const students = await db.student.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, studentId: true, firstName: true, lastName: true },
  });
  const studentMap = new Map(students.map((s) => [s.id, s]));

  const receiverIds = [...new Set(payments.map((p) => p.receivedBy))];
  const receivers = await db.user.findMany({
    where: { id: { in: receiverIds } },
    select: { id: true, firstName: true, lastName: true },
  });
  const receiverMap = new Map(receivers.map((r) => [r.id, `${r.firstName} ${r.lastName}`]));

  const data = payments.map((payment) => {
    const student = studentMap.get(payment.studentId);
    return {
      ...payment,
      studentName: student ? `${student.firstName} ${student.lastName}` : "Unknown",
      studentIdNumber: student?.studentId ?? "Unknown",
      receivedByName: receiverMap.get(payment.receivedBy) ?? "Unknown",
      receiptNumber: payment.receipt?.receiptNumber ?? null,
    };
  });

  return {
    data,
    pagination: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) },
  };
}

export async function getPaymentAction(id: string) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_READ);
  if (denied) return denied;

  const payment = await db.payment.findUnique({
    where: { id },
    include: {
      receipt: true,
      reversal: true,
      studentBill: {
        include: {
          billItems: { include: { feeItem: true } },
          feeStructure: { select: { id: true, name: true } },
        },
      },
    },
  });

  if (!payment) return { error: "Payment not found" };

  const student = await db.student.findUnique({
    where: { id: payment.studentId },
    select: { id: true, studentId: true, firstName: true, lastName: true },
  });

  const receiver = await db.user.findUnique({
    where: { id: payment.receivedBy },
    select: { id: true, firstName: true, lastName: true },
  });

  return {
    data: {
      ...payment,
      studentName: student ? `${student.firstName} ${student.lastName}` : "Unknown",
      studentIdNumber: student?.studentId ?? "Unknown",
      receivedByName: receiver ? `${receiver.firstName} ${receiver.lastName}` : "Unknown",
    },
  };
}

export async function getDailyCollectionAction(date: string) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_READ);
  if (denied) return denied;

  const dateStart = new Date(date);
  dateStart.setHours(0, 0, 0, 0);
  const dateEnd = new Date(date);
  dateEnd.setHours(23, 59, 59, 999);

  const payments = await db.payment.findMany({
    where: { receivedAt: { gte: dateStart, lte: dateEnd }, status: "CONFIRMED" },
    include: { receipt: true },
  });

  const studentIds = [...new Set(payments.map((p) => p.studentId))];
  const students = await db.student.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, studentId: true, firstName: true, lastName: true },
  });
  const studentMap = new Map(students.map((s) => [s.id, s]));

  const grouped: Record<string, { payments: typeof payments; total: number }> = {};
  let grandTotal = 0;

  for (const payment of payments) {
    const method = payment.paymentMethod;
    if (!grouped[method]) grouped[method] = { payments: [], total: 0 };
    grouped[method].payments.push(payment);
    grouped[method].total += toNum(payment.amount);
    grandTotal += toNum(payment.amount);
  }

  const data = payments.map((p) => {
    const student = studentMap.get(p.studentId);
    return {
      ...p,
      studentName: student ? `${student.firstName} ${student.lastName}` : "Unknown",
      studentIdNumber: student?.studentId ?? "Unknown",
      receiptNumber: p.receipt?.receiptNumber ?? null,
    };
  });

  return {
    data,
    summary: {
      byMethod: Object.entries(grouped).map(([method, info]) => ({
        method,
        count: info.payments.length,
        total: info.total,
      })),
      grandTotal,
      totalPayments: payments.length,
    },
  };
}

export async function initiateReversalAction(data: InitiateReversalInput) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_REVERSE);
  if (denied) return denied;

  const parsed = initiateReversalSchema.safeParse(data);
  if (!parsed.success) return { error: "Invalid input", details: parsed.error.flatten().fieldErrors };

  const payment = await db.payment.findUnique({
    where: { id: parsed.data.paymentId },
    include: { reversal: true },
  });
  if (!payment) return { error: "Payment not found" };
  if (payment.status === "REVERSED") return { error: "Payment has already been reversed" };
  if (payment.reversal) return { error: "A reversal request already exists for this payment" };

  const reversal = await db.paymentReversal.create({
    data: {
      schoolId: ctx.schoolId,
      paymentId: payment.id,
      reason: parsed.data.reason,
      reversedBy: ctx.session.user.id!,
      status: "PENDING",
    },
  });

  await audit({
    userId: ctx.session.user.id,
    action: "CREATE",
    entity: "PaymentReversal",
    entityId: reversal.id,
    module: "finance",
    description: `Initiated payment reversal for payment ${payment.id}. Reason: ${parsed.data.reason}`,
    newData: reversal,
  });

  return { data: reversal };
}

export async function approveReversalAction(reversalId: string) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_REVERSE);
  if (denied) return denied;

  const reversal = await db.paymentReversal.findUnique({
    where: { id: reversalId },
    include: {
      payment: { include: { studentBill: true } },
    },
  });

  if (!reversal) return { error: "Reversal not found" };
  if (reversal.status !== "PENDING") return { error: "Reversal is not in PENDING status" };

  try {
    await db.$transaction(async (tx) => {
      await tx.paymentReversal.update({
        where: { id: reversalId },
        data: {
          status: "APPROVED",
          approvedBy: ctx.session.user.id!,
          approvedAt: new Date(),
        },
      });

      await tx.payment.update({
        where: { id: reversal.paymentId },
        data: { status: "REVERSED" },
      });

      // Recalculate bill status
      const bill = reversal.payment.studentBill;
      const newPaidAmount = toNum(bill.paidAmount) - toNum(reversal.payment.amount);
      const newBalanceAmount = toNum(bill.totalAmount) - newPaidAmount;

      let newStatus: "UNPAID" | "PARTIAL" | "PAID" | "OVERPAID";
      if (newPaidAmount <= 0) newStatus = "UNPAID";
      else if (newBalanceAmount <= 0) newStatus = "PAID";
      else newStatus = "PARTIAL";

      await tx.studentBill.update({
        where: { id: bill.id },
        data: {
          paidAmount: Math.max(0, newPaidAmount),
          balanceAmount: Math.max(0, newBalanceAmount),
          status: newStatus,
        },
      });

      // Reverse the original payment journal to undo cash receipt
      if (reversal.payment.journalTransactionId) {
        const reversalTxn = await reverseJournalTransaction(tx, reversal.payment.journalTransactionId, {
          schoolId: ctx.schoolId,
          reversedBy: ctx.session.user.id!,
          description: `Reversal of payment ${reversal.payment.id.slice(-8)} — ${reversal.reason}`,
        });
        await tx.paymentReversal.update({
          where: { id: reversalId },
          data: { journalTransactionId: reversalTxn.journalTransactionId },
        });
      }
    });

    await audit({
      userId: ctx.session.user.id,
      action: "UPDATE",
      entity: "PaymentReversal",
      entityId: reversalId,
      module: "finance",
      description: `Approved payment reversal for payment ${reversal.paymentId}`,
      newData: { status: "APPROVED" },
    });

    return { success: true };
  } catch (err) {
    if (err instanceof LedgerError) return { error: `Ledger posting failed: ${err.message}` };
    throw err;
  }
}

export async function rejectReversalAction(reversalId: string) {
  const ctx = await requireSchoolContext();
  if ("error" in ctx) return ctx;
  const denied = assertPermission(ctx.session, PERMISSIONS.PAYMENTS_REVERSE);
  if (denied) return denied;

  const reversal = await db.paymentReversal.findUnique({ where: { id: reversalId } });
  if (!reversal) return { error: "Reversal not found" };
  if (reversal.status !== "PENDING") return { error: "Reversal is not in PENDING status" };

  await db.paymentReversal.update({
    where: { id: reversalId },
    data: { status: "REJECTED" },
  });

  await audit({
    userId: ctx.session.user.id,
    action: "UPDATE",
    entity: "PaymentReversal",
    entityId: reversalId,
    module: "finance",
    description: `Rejected payment reversal for payment ${reversal.paymentId}`,
    newData: { status: "REJECTED" },
  });

  return { success: true };
}
